export default {
  // sync
  ADD_DUMMY: 'ADD_DUMMY',
  UPDATE_BOOK: 'UPDATE_BOOK',

  // async
  FETCH_BOOK_LIST_PENDING: 'FETCH_BOOK_LIST_PENDING',
  FETCH_BOOK_LIST_SUCCESS: 'FETCH_BOOK_LIST_SUCCESS',
  FETCH_BOOK_LIST_ERROR: 'FETCH_BOOK_LIST_ERROR',
  FETCH_BOOK_DETAILS_PENDING: 'FETCH_BOOK_DETAILS_PENDING',
  FETCH_BOOK_DETAILS_SUCCESS: 'FETCH_BOOK_DETAILS_SUCCESS',
  FETCH_BOOK_DETAILS_ERROR: 'FETCH_BOOK_DETAILS_ERROR',
  FETCH_BOOK_EDIT_PENDING: 'FETCH_BOOK_EDIT_PENDING',
  FETCH_BOOK_EDIT_SUCCESS: 'FETCH_BOOK_EDIT_SUCCESS',
  FETCH_BOOK_EDIT_ERROR: 'FETCH_BOOK_EDIT_ERROR',
  PERSIST_BOOK_PENDING: 'PERSIST_BOOK_PENDING',
  PERSIST_BOOK_SUCCESS: 'PERSIST_BOOK_SUCCESS',
  PERSIST_BOOK_ERROR: 'PERSIST_BOOK_ERROR',
  CREATE_BOOK_PENDING: 'CREATE_BOOK_PENDING',
  CREATE_BOOK_SUCCESS: 'CREATE_BOOK_SUCCESS',
  CREATE_BOOK_ERROR: 'CREATE_BOOK_ERROR',
}
